name: Create Diagram
on:
  workflow_dispatch: {}
  push:
    branches: 
      - main
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: Rikkert33/RL-Imitation-Learning-V1@main
        with:
          excluded_paths: "irgnore,.github"
